title: nonnenmacher.DEV
author: Fabian Nonnenmacher
email: your-email@domain.com
description: > # this means to ignore newlines until "show_exerpts:"
  Fabian Nonnenmacher's personal blog. Fabian is a software developer excited about learning new stuff. I mainly work
  within the JVM ecosystem and are fascinated by cloud applications and modern software development methods and approaches.
show_excerpts: true # set to true to show excerpts on the homepage
#baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /blog/:title/
texture:
  title: Fabian Nonnenmacher
  tagline: Software Developer Enthusiast
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    twitter: fabnon93
    github:  fnonnenmacher
    linkedIn: in/fnonnenmacher
    rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed